project_id = "dkojbzxixkgawfhggkmy"

[functions.analyze-product-image]
verify_jwt = true

[functions.calculate-shipping]
verify_jwt = false

[functions.create-mercado-pago-payment]
verify_jwt = true

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false
